### PR TITLE
Allow to mount workspace from run directory via WebDAV

### PR DESCRIPTION
**Pull request by Xarthisius**
Same principle as regular `wt_work`, just use `run_id`...

### CODE REVIEW

**Comment by craig-willis** [comment]
The way I'm implementing the recorded_run task, I'm building the image before the run. This means I need the environment.json in the workspace (or in .wholetale directory).  For the moment, I'm dumping it to the workspace during the run, but wonder if it would be better to mount via this PR?

**Comment by Xarthisius** [comment]
> I'm dumping it to the workspace during the run, but wonder if it would be better to mount via this PR?

We can, but don't we dump the environment.json to the copy of a workspace for regular tale build already? Why make it different?

**Comment by hategan** [comment]
Is this necessary? I mean, isn't it easier (i.e., requiring no new code) to mount all runs using the existing FS mode and link to/point to the relevant run?

**Comment by Xarthisius** [comment]
> Is this necessary? I mean, isn't it easier (i.e., requiring no new code) to mount all runs using the existing FS mode and link to/point to the relevant run?

I want to avoid situation when user does something silly, like try to read the files from previous runs in the current run. Whether we try to isolate it via proper mount bind from a specific folder from `wt_runs`, or we expose proper directory via webdav seemed to require similar amount of effort / new code.

**Comment by hategan** [comment]
> > Is this necessary? I mean, isn't it easier (i.e., requiring no new code) to mount all runs using the existing FS mode and link to/point to the relevant run?
> 
> I want to avoid situation when user does something silly, like try to read the files from previous runs in the current run. Whether we try to isolate it via proper mount bind from a specific folder from `wt_runs`, or we expose proper directory via webdav seemed to require similar amount of effort / new code.

You can mount runs with restrictive access then bind-mount a specific subdir with normal perms all with standard linux tools.

**Comment by Xarthisius** [comment]
> You can mount runs with restrictive access then bind-mount a specific subdir with normal perms all with standard linux tools.

That's what I wrote above as an option a). then I wrote that option b) is pretty much equivalent in terms of code length that needs to happen.

**Comment by hategan** [comment]
> > You can mount runs with restrictive access then bind-mount a specific subdir with normal perms all with standard linux tools.
> 
> That's what I wrote above as an option a). then I wrote that option b) is pretty much equivalent in terms of code length that needs to happen.

Sorry. It was my misperception of the relative sizes of the two. I agree this looks like the better solution.

**Review by craig-willis — APPROVED** [review]
This is working for me. As discussed, I am writing the environment.json to .wholetale and removing at the end of the run.

**Comment by craig-willis** [comment]
When testing this I had a local change for `sys.maxsize` (lowercase):

https://github.com/whole-tale/girderfs/blob/run_dir/girderfs/dms.py#L29

**Comment by Xarthisius** [comment]
> When testing this I had a local change for `sys.maxsize` (lowercase):
> 
> https://github.com/whole-tale/girderfs/blob/run_dir/girderfs/dms.py#L29

That went in https://github.com/whole-tale/girderfs/pull/26/commits/06e73bb5bde7da797677f3156def8367af278485

**Pull request merged**
