### PR TITLE
Move all the things into separate modules

### PR DESCRIPTION
**Pull request by Xarthisius**
I personally love when everything is in a one file. Preferably `main.f`. However, things here were getting slightly out of hand. This should be noop PR, I'm just moving things around.

### CODE REVIEW

**Comment by hategan** [comment]
This has been long overdue.

I'd go as far as saying that a full re-design is overdue here.

**Comment by Xarthisius** [comment]
> This has been long overdue.
> 
> I'd go as far as saying that a full re-design is overdue here.

I'm trying to do it incrementally ;)

**Comment by hategan** [comment]
> I'm trying to do it incrementally

As opposed to all-in-one? I don't know...

**Comment by Xarthisius** [comment]
> As opposed to all-in-one? I don't know...

I considered reimplementing everything from scratch in Go, but where's the fun in that?

**Review by craig-willis — APPROVED** [review]
Working for me.

**Pull request merged**
